### ISSUE TITLE
Make it easier to run the integration tests locally

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/image-builder#106]
The unit tests with `go test ./...` are pretty straightforward.

The integration tests (`cmd/image-builder-tests`) require composer up and running, and also a container of image-builder to test the container variant; so they are harder to run.

Either have a script somewhere or a make target before running `go test -tags=integration`. And document it.

**Comment by teg** [comment]
Maybe we could reuse/extend the docker compose stuff @achilleas-k made for osbuild-composer?

**Comment by yuxisun1217** [comment]
Thanks @Gundersanne !
The unit tests I've run the 4 cases successfully. And there's a new package "tutils" has no unit test yet.
```
ok  	github.com/osbuild/image-builder/cmd/image-builder	0.011s
ok  	github.com/osbuild/image-builder/internal/cloudapi	0.010s
ok  	github.com/osbuild/image-builder/internal/logger	0.176s
ok  	github.com/osbuild/image-builder/internal/server	3.557s
?   	github.com/osbuild/image-builder/internal/tutils	[no test files]
```

About the integration test, I found a jenkinsfile "schutzbot/Jenkinsfile" and followed it to build the image-builder packages, install it in my fedora33, start a container and run image-builder-test, and get PASS result:
```
# /usr/libexec/tests/image-builder/image-builder-tests -test.v | tee /root/image-builder-test.log
=== RUN   TestImageBuilder

Out:  time="2021-01-25T06:13:16Z" level=info msg="🚀 Starting image-builder server on localhost:8086 ...\n" func="github.com/osbuild/image-builder/internal/server.(*Server).Run" file="/builddir/build/BUILD/image-builder-87143554f2f6f8042f36c0401ba08e0313409fe7/_build/src/github.com/osbuild/image-builder/internal/server/server.go:67"

   ____    __
  / __/___/ /  ___
 / _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.1.17
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
                                    O\
⇨ http server started on 127.0.0.1:8086

--- PASS: TestImageBuilder (11.48s)
=== RUN   TestImageBuilderContainer
--- PASS: TestImageBuilderContainer (9.28s)
PASS
```
* I also get the same result when I go to /root/repos/image-builder/cmd/image-builder-tests/ and run "go test -tags=integration"

BTW, since there is a jenkinsfile, is there a CI job somewhere? Thanks!

**Comment by yuxisun1217** [comment]
Hi @teg ,

Is the "osbuild-composer" the job that runs this jenkinsfile?

**Comment by Gundersanne** [comment]
So `tutils` is test utils, it's only stuff that's used during unit tests themselves.

And the CI should run on each PR hosted on psi. The integration tests are kinda weird in that there's 2 tests, one which starts image-builder itself, and the other one which expects there to be an image-builder container running. The latter is started right before running the actual tests.


> Maybe we could reuse/extend the docker compose stuff @achilleas-k made for osbuild-composer?

Maybe! where is it ?

**Comment by achilleas-k** [comment]
PR is still open for it here https://github.com/osbuild/osbuild-composer/pull/1146
