### ISSUE TITLE
Please reduce Gitlab hosted runner minutes

### ISSUE THREAD

**Issue by sgallagher** [osbuild/image-builder#1242]
The Red Hat organization in Gitlab has a limited number of compute minutes available from the Gitlab hosted runners each month. As of today, this project has used 30% of those minutes. There are still ten days left in the month, so the current usage rate is untenable.

We need to reduce the number of pipeline minutes being consumed by this project by either reducing the number of runs you are performing or else switching to Red Hat self-hosted runners so as not to consume the Gitlab minutes. If you need assistance with setting up self-hosted runners, please reach out to myself or the [linux-eng-gitlab-admins@redhat.com](mailto:linux-eng-gitlab-admins@redhat.com) mailing list.

**Comment by ezr-ondrej** [comment]
@ochosi, @croissanne, @jrusz should we meetup and discuss what we can do here?

**Comment by ochosi** [comment]
We're mostly using self-hosted runners.
Pinged @narmaku to investigate cloud-image-val's usage of gitlab hosted runners.

**Comment by ondrejbudai** [comment]
The other offender are the unfortunate null jobs in `images`, a PR to fix that: https://github.com/osbuild/images/pull/759

**Comment by narmaku** [comment]
@ochosi , as discussed internally, we have now specified the self-hosted "shell" runner for cloud-image-val's `init` and `finish` stages, which were using shared runners. Commit: https://github.com/osbuild/cloud-image-val/commit/b37b4874e11efaf6311c34dfc726eb3de43f047e

**Comment by ondrejbudai** [comment]
We shouldn't be using the hosted runners anymore after these changes. Closing this issue. Please, reach out to us if this becomes a problem again. :)
