### ISSUE TITLE
 crypt doesn't work on macos 

### ISSUE THREAD

**Issue by mgold1234** [osbuild/image-builder#1293]
when I run unit test on my Mac computer I got this stack of error:
```=== RUN   TestBlueprintBody_CryptPasswords
--- FAIL: TestBlueprintBody_CryptPasswords (0.00s)
panic: You must not run osbuild-composer on macOS! [recovered]
        panic: You must not run osbuild-composer on macOS!

goroutine 674 [running]:
testing.tRunner.func1.2({0x103bdbd20, 0x103d0b220})
        /Users/michalgold/go/go1.22.4/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
        /Users/michalgold/go/go1.22.4/src/testing/testing.go:1634 +0x33c
panic({0x103bdbd20?, 0x103d0b220?})
        /Users/michalgold/go/go1.22.4/src/runtime/panic.go:770 +0x124
github.com/osbuild/images/pkg/crypt.crypt(...)
        /Users/michalgold/git/edge-management/image-builder-project/image-builder/vendor/github.com/osbuild/images/pkg/crypt/crypt_impl_macos.go:6
github.com/osbuild/images/pkg/crypt.CryptSHA512({0x1036688cb, 0xb})
        /Users/michalgold/git/edge-management/image-builder-project/image-builder/vendor/github.com/osbuild/images/pkg/crypt/crypt.go:27 +0x118
github.com/osbuild/image-builder/internal/v1.(*User).CryptPassword(0x14000857e18)
        /Users/michalgold/git/edge-management/image-builder-project/image-builder/internal/v1/handler_blueprints.go:48 +0x110
github.com/osbuild/image-builder/internal/v1.(*BlueprintBody).CryptPasswords(0x14000857e70)
        /Users/michalgold/git/edge-management/image-builder-project/image-builder/internal/v1/handler_blueprints.go:70 +0x80
github.com/osbuild/image-builder/internal/v1.TestBlueprintBody_CryptPasswords(0x1400a1b0d00)
        /Users/michalgold/git/edge-management/image-builder-project/image-builder/internal/v1/handler_blueprints_test.go:785 +0xec
testing.tRunner(0x1400a1b0d00, 0x103d07340)
        /Users/michalgold/go/go1.22.4/src/testing/testing.go:1689 +0xec
created by testing.(*T).Run in goroutine 1
        /Users/michalgold/go/go1.22.4/src/testing/testing.go:1742 +0x318
FAIL    github.com/osbuild/image-builder/internal/v1    5.144s
FAIL
```

**Comment by mvo5** [comment]
Thanks for reporting this! The error comes from https://github.com/osbuild/images/blob/main/pkg/crypt/crypt_impl_macos.go - I guess this could be somewhat improved by simply also not running the TestBlueprintBody_CryptPasswords on macos.

**Comment by mgold1234** [comment]
@mvo5 thank you, what do you think about adding a support in macOS https://github.com/osbuild/images/pull/855
all the unit test was working before https://github.com/osbuild/image-builder/pull/1283 , I think it should continue to work

**Comment by ezr-ondrej** [comment]
I'm guessing it's not as easy, but it would be good to understand why it's the case :)

**Comment by mvo5** [comment]
Something like:
```go
diff --git a/pkg/crypt/crypt_impl_macos.go b/pkg/crypt/crypt_impl_macos.go
index b1c8e9bb0..8dcdd465b 100644
--- a/pkg/crypt/crypt_impl_macos.go
+++ b/pkg/crypt/crypt_impl_macos.go
@@ -2,6 +2,45 @@
 
 package crypt
 
+/*
+       #include <stdlib.h>
+       #include <string.h>
+       #include <unistd.h>
+
+       char *crypt(char *pass, char *salt) {
+               char *enc = NULL;
+               char *ret = NULL;
+
+               enc = crypt(pass, salt);
+               if(enc == NULL) {
+                       return NULL;
+               }
+
+               ret = (char *)malloc((strlen(enc)+1) * sizeof(char)); // for trailing null
+               strcpy(ret, enc);
+               ret[strlen(enc)]= '\0';
+
+        return ret;
+       }
+*/
+import "C"
+
+// Crypt provides a wrapper around the macos crypt() function.
 func crypt(pass, salt string) (string, error) {
-       panic("You must not run osbuild-composer on macOS!")
+       c_pass := C.CString(pass)
+       defer C.free(unsafe.Pointer(c_pass))
+
+       c_salt := C.CString(salt)
+       defer C.free(unsafe.Pointer(c_salt))
+
+       c_enc, err := C.crypt(c_pass, c_salt)
+       if c_enc == nil {
+               return "", err
+       }
+       defer C.free(unsafe.Pointer(c_enc))
+
+       // Return nil error if the string is non-nil.
+       // As per the errno.h manpage, functions are allowed to set errno
+       // on success. Caller should ignore errno on success.
+       return C.GoString(c_enc), nil
 }

```
might work (but I have no mac so can't test).

**Comment by mgold1234** [comment]
I tried that and now I am getting this ```GOROOT=/Users/michalgold/go/go1.22.4 #gosetup
GOPATH=/Users/michalgold/go #gosetup
/Users/michalgold/go/go1.22.4/bin/go test -c -o /Users/michalgold/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestBlueprintBody_CryptPasswords_in_github_com_osbuild_image_builder_internal_v1.test -gcflags all=-N -l github.com/osbuild/image-builder/internal/v1 #gosetup
# github.com/osbuild/images/pkg/crypt
../../vendor/github.com/osbuild/images/pkg/crypt/crypt_impl_macos.go:12:7: error: conflicting types for 'crypt'
char *crypt(char *pass, char *salt) {
      ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:544:7: note: previous declaration is here
char    *crypt(const char *, const char *);
         ^
1 error generated.
````

**Comment by mvo5** [comment]
> I tried that and now I am getting this
> 
> ```
> ../../vendor/github.com/osbuild/images/pkg/crypt/crypt_impl_macos.go:12:7: error: conflicting types for 'crypt'
> char *crypt(char *pass, char *salt) {
>       ^
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:544:7: note: previous declaration is here
> char    *crypt(const char *, const char *);
>          ^
> 1 error generated.```
> ```

Thanks for testing and silly me - I updated the diff, hope this one works better.

**Comment by mgold1234** [comment]
we will skip relevant tests that failing

**Comment by mgold1234** [comment]
https://github.com/osbuild/image-builder/pull/1297
