### ISSUE TITLE
image builds stuck in prod

### ISSUE THREAD

**Issue by teg** [osbuild/image-builder#191]
Image builds appear to be stuck in production. I did not yet dig deeper.
<img width="1458" alt="Screenshot 2021-05-28 at 11 44 14" src="https://user-images.githubusercontent.com/5409/119972572-47824f80-bfaa-11eb-9357-cc22f7053aa7.png">

**Comment by Gundersanne** [comment]
I have a few of these as well, same on stage. It's not an image-builder issue though, composer keeps reporting them as running :/

**Comment by ondrejbudai** [comment]
We have heartbeats now to prevent this, right?

**Comment by Gundersanne** [comment]
This was solved with osbuild/osbuild-composer#1523
