### ISSUE TITLE
Need pre-check dos2unix package in test/cases/api.sh

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/image-builder#195]
Once we migrate to GitLab the runners will come with some epositories pre-configured sometimes.

If want this to be a robust check then remove/disable everything under /etc/yum.repos.d before subscribing but still keep the rpm -q dos2unix check. That's a pre-condition and we want to fail if the pre-condition isn't met.

**Comment by yuxisun1217** [comment]
Hi @atodorov ,
We also don't need the package installation check in image-builder api.sh right? If yes I'll open a PR to remove the step and close this issue then. Thanks!

**Comment by atodorov** [comment]
It works like it is ATM so no changes are needed.
