### ISSUE TITLE
Use jackc/tern for database migration

### ISSUE THREAD

**Issue by croissanne** [osbuild/image-builder#197]
Currently we depend on `lib/pq` for migrations and `jackc` for the actual db operations. It makes sense to move the migrations over to `jackc/tern`. Furthermore `lib/pq` doesn't support sslmode `prefer`, which should be the sensible default.

**Comment by Gundersanne** [comment]
Should be possible to install tern in the container, all we need to do is make sure the schemas are compatible.

**Comment by Gundersanne** [comment]
Best approach here:

- Migrate a db with the current tool
- Try it with tern on the same database
- Make sure it works fine
- Drop the old tool and keep tern
