### ISSUE TITLE
subscription test cases failed randomly

### ISSUE THREAD

**Issue by yuxisun1217** [osbuild/image-builder#199]
Sometimes the subscription test failed. The VM is not registered after boot up. e.g.
https://osbuildci.cloud.paas.psi.redhat.com/job/osbuild/job/image-builder/job/main/79/execution/node/65/log/
```
17:07:30  ++ ssh -oStrictHostKeyChecking=no -i ./keypair.pem cloud-user@3.143.234.201 sudo subscription-manager identity
17:07:30  ++ grep 'org ID'
17:07:30  This system is not yet registered. Try 'subscription-manager register --help' for more information.
17:07:30  + subscribe_org_id=
```

Perhaps need to wait or loop retry several times to verify it.

**Comment by atodorov** [comment]
FTR I don't think this is random but a race condition. I saw it yesterday with the GCP test and after restarting without modification it passed. 

What I think is happening is that we're able to ssh into the VM before the registration code has managed to execute.  My proposal is to try checking for subscriptions inside a loop+sleep, say 10 times with 30 sec sleep.

If the subscription check still fails then we need to extract some logs from the VM to actually figure out what is happening there.

**Comment by Gundersanne** [comment]
Thank you! Let's close this for now, if it reoccurs we'll reopen it?

**Comment by Gundersanne** [comment]
Just reoccurred, making a PR to increase the timeout.
