### ISSUE TITLE
metrics: ensure compose 500 are genuine

### ISSUE THREAD

**Issue by teg** [osbuild/image-builder#216]
Verify that we don't consider user error as a failure, only true internal errors.

This might mostly be a composer issue.

**Comment by kingsleyzissou** [comment]
I have a WIP for the worker metrics and tested this locally. So far it looks like the 500 errors are genuine and
`4xx` errors aren't counted in the metrics. I'll carry on testing this a bit more though over the next few days.

**Comment by kingsleyzissou** [comment]
This looks like it is fine:

![image](https://user-images.githubusercontent.com/20438192/151976017-b585c27f-3d15-4823-b91a-b886957c2c2c.png)

![image](https://user-images.githubusercontent.com/20438192/151976180-eff51dc0-5cdc-46be-bd37-3dd503274374.png)
