### ISSUE TITLE
The default user on `ami` image type changed since RHEL-8.5

### ISSUE THREAD

**Issue by thozza** [osbuild/image-builder#226]
The `ami` image type have been redefined since RHEL-8.5 based on the official RHEL EC2 images (https://github.com/osbuild/osbuild-composer/pull/1607). As a result, the username of the default user created by cloud-init changed from `cloud-user` to `ec2-user`. 

This required a change in the Cloud API test case (`api.sh`) in osbuild-composer:
https://github.com/osbuild/osbuild-composer/blob/53109945efb4ff648982fc6c52af723dede63bd5/test/cases/api.sh#L391-L396

An equivalent change will be needed in the `api.sh` test case of image-builder, once it will start to be tested with RHEL-8.5:
https://github.com/osbuild/image-builder/blob/5a7b6ca56d499fc6dbbd703fc9930ba498c9277d/test/cases/api.sh#L137-L139

**Comment by kingsleyzissou** [comment]
This has been fixed with https://github.com/osbuild/image-builder/blob/1f735991d7426de9d496f4c3fffc6ea49dbadcd9/test/cases/api.sh#L122-L124
