### ISSUE TITLE
Rate limiting of image builds

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/image-builder#247]
- Per account_number
- Each account_number is able to have it's own limit (some accounts may be allowed more builds than others)
- Limit per 2 week period?

**Comment by Gundersanne** [comment]
Implemenation:
- This list should not live upstream, but mapped to the container (as a configmap? can we define this list in app-intf?)
- This should not require any changes in the db migrations since all entries already carry a timestamp + account number

**Comment by Gundersanne** [comment]
@teg So say the jobs keep failing (you started 100 image builds and they all failed). Do we wanna count those towards the limit?

**Comment by teg** [comment]
Good question!

I would say no, the quota should be on the number of images we store.

Might also want a second (much higher) limit on the number of (attempted) image builds to avoid someone DoS'ing us with failing builds.

**Comment by Gundersanne** [comment]
> I would say no, the quota should be on the number of images we store.

So currently we store all images, but should this have a time limit as well? Like the amount of images stored in the past 14 days?


> Might also want a second (much higher) limit on the number of (attempted) image builds to avoid someone DoS'ing us with failing builds.

**Comment by teg** [comment]
Yeah, that was what I was thinking: put the quote on the number of stored images in the past 14 days, under the assumption we delete images after 14 days.

**Comment by Gundersanne** [comment]
That's gonna be a bit harder because we need the final status of each of those builds then. So we'd need to query composer for each of the builds they did in the past 14 days. Not sure if that's a good idea.

**Comment by teg** [comment]
Ah, we can definitely use the number of attempted builds as an approximation for now, but yeah we should figure out a long term plan

**Comment by Gundersanne** [comment]
Let's have a generous default for now, and then long term let's see,  I think we can't really do this in any reasonable sense without having IB store/cache the result.
