### ISSUE TITLE
When receiving the IMAGE-BUILDER-COMPOSER-15 error return a 404 instead of 500

### ISSUE THREAD

**Issue by Gundersanne** [osbuild/image-builder#289]
A lot of old IDs don't exist anymore, which is actually expected behaviour. So let's just return 404.

**Comment by kingsleyzissou** [comment]
Looks like this has been sorted

![image](https://user-images.githubusercontent.com/20438192/151183865-31665c94-7f5b-4291-bab6-fd9017f933ae.png)
