### ISSUE TITLE
Return 400 if route note found or bad method

### ISSUE THREAD

**Issue by croissanne** [osbuild/image-builder#426]
https://github.com/osbuild/image-builder/blob/7bf6468c6e1f2c4518283ba0712a34d00eb012c7/internal/v1/middleware.go#L10-L31

`FindRoute` returns ErrPathNotFound or ErrMethodNotAllowed, both should result in a 400. Currently ib returns a 500.

**Comment by Gundersanne** [comment]
[github.com/getkin/kin-openapi/router](https://github.com/osbuild/image-builder/pull/452#pullrequestreview-1123755399) ;

ErrPathNotFound -> 404
ErrMethodNotAllowed -> 405
