### ISSUE TITLE
ComposeImage should return 400 if distribution doesn't exist

### ISSUE THREAD

**Issue by croissanne** [osbuild/image-builder#584]
`/compose` returns 500 if a requested distribution doesn't exist or if the user is not entitled to it. This should be 400.

**Comment by elkoniu** [comment]
Right now based on the `handler_post_compose_test.go` return codes are:
- 201 when user requires restricted distribution but it is allowed by allow file
- 403 when user requires restricted distribution and it is not allowed by allow file
- 403 when user requites restricted distribution and there is no allow file
- 500 when user requires status of compose for non existing compose
