### ISSUE TITLE
Reconsider testing on EL8 with Schutzbot

### ISSUE THREAD

**Issue by atodorov** [osbuild/image-builder#60]
Currently I see this in Jenkinsfile:
```
// TODO osbuild-composer-api isn't available in rhel8
// stage('EL8') {
```

however for clouddot we're expected to be deploying this on an EL8 system so IMO it makes sense to continue testing even if we don't ship any RPMs.

Are there any issues/problems preventing us from building and testing on EL8 ?

**Comment by Gundersanne** [comment]
These were enabled again in #59, as the osbuild-composer package now gets installed via our own rpm repos where we can pin an exact composer version. See `OSBUILD_COMPOSER_COMMIT` in https://github.com/osbuild/image-builder/blob/master/schutzbot/provision-composer.sh.

Before we had an older version of composer on rhel which didn't have the cloudapi part.

As this is solved now I'll close it.
